name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest tests/

      - name: Build
        run: |
          # Include any build steps here, e.g., compiling assets, etc.

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          # Add commands to deploy to staging environment

      - name: Deploy to Production
        if: github.event_name == 'release'
        run: |
          # Add commands to deploy to production environment
